export const defaultState = {
  index: 0,
  height: 0,
  age: 0,
  sex: "",
  resultAdult: 0,
  childheight: 0,
  childage: 0,
  childweight: 0,
  childgender: "",
  childresult: 0,
  childageindicator: "month",
  childheightindicator: "cm",
  ulnalength:0,
  demispan:0,
  warning: "",
  error: "",
  errorAdult: "",
};
